### ISSUE TITLE
Wrong week shown in the week starting in one and ending in another year

### ISSUE THREAD

**Issue by 4D44H** [4D44H/lara-vedst#9]
Current status:
- In the end of 2014 instead of week 01 2015 in "current week" view week 01 2014 is shown
- reason: CalenderController@currentWeek() gets current year and current week from PHP function date() - receives "2014" and "01" back. Should be "2014 + "53" or "2015" + "01".

ToDo:
- rewrite currentYear() and currentWeek() in CalenderController

**Comment by bobcanthelpyou** [comment]
Maybe we should use date('o') instead of date('Y') in currentWeek() and it shows the correct year to the week number. But there is only one valid week number for a week (ISO 8601). https://php.net/manual/en/function.date.php

Examples:
```
$date='28.12.2014';
for ($i=0;$i<9;$i++) {
        echo date("d.m.Y - W. \K\W o",strtotime($date)+($i*24*60*60))."\n";
}
```
28.12.2014 - 52. KW 2014
29.12.2014 - 01. KW 2015
30.12.2014 - 01. KW 2015
31.12.2014 - 01. KW 2015
01.01.2015 - 01. KW 2015
02.01.2015 - 01. KW 2015
03.01.2015 - 01. KW 2015
04.01.2015 - 01. KW 2015
05.01.2015 - 02. KW 2015

```
$date='27.12.2009';
for ($i=0;$i<9;$i++) {
        echo date("d.m.Y - W. \K\W o",strtotime($date)+($i*24*60*60))."\n";
}
```
27.12.2009 - 52. KW 2009
28.12.2009 - 53. KW 2009
29.12.2009 - 53. KW 2009
30.12.2009 - 53. KW 2009
31.12.2009 - 53. KW 2009
01.01.2010 - 53. KW 2009
02.01.2010 - 53. KW 2009
03.01.2010 - 53. KW 2009
04.01.2010 - 01. KW 2010

**Comment by 4D44H** [comment]
@bobcanthelpyou Looks like this should be enough. Could you make a pull request?

**Comment by 4D44H** [comment]
It's even worth in 2016, needs a fix ASAP.

**Comment by 4D44H** [comment]
Fixed in WeekController@showWeek() and followed by some rewriting of the weekVIew.blade.php.
